# Generated by Django 3.0.7 on 2020-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_target_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
