jobs:
  build:
    docker:
      - image: circleci/python:3.7.7
      - image: circleci/postgres:alpine-postgis-ram
        environment:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_pass
          POSTGRES_DB: ci_db
    environment:
      SECRET_KEY: ksjdbfjksdbfksd3434bj34
      DB_NAME: ci_db
      DB_USER: ci_user
      DB_PASSWORD: ci_pass
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
    steps:
      - checkout
      - run:
          name: Updating pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip==20.0.2
      - run:
          name: Installing pip requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ./requirements.txt
      # - run:
      #     name: Checking PEP8 code style
      #     command: |
      #       . venv/bin/activate
      #       flake8 --count --exclude=.git,*migrations*,venv/* --max-line-length=119
      - run:
          name: Installing GDAL
          command: |
            sudo apt-get install libgdal-dev
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            coverage run --omit=venv/* --source="." manage.py test
      # - run:
      #     name: Checking coverage
      #     command: |
      #       . venv/bin/activate
      #       coverage report --omit=venv/*,manage.py --fail-under=90
