version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest
      - image: circleci/postgres:alpine-postgis-ram
    steps:
      - checkout
      - run:
          name: Updating pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip==20.0.2
      - run:
          name: Installing pip requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ./requirements.txt
      - run: cp .circleci/ci.env ./.env
      - run:
          name: Checking PEP8 code style
          command: |
            . venv/bin/activate
            flake8 --count --exclude=.git,*migrations*,venv/* --max-line-length=119
      - run:
          name: Installing GDAL
          command: |
            sudo apt-get install libgdal-dev
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            coverage run --omit=venv/* --source="." manage.py test
      # - run:
      #     name: Checking coverage
      #     command: |
      #       . venv/bin/activate
      #       coverage report --omit=venv/*,manage.py --fail-under=90
